#STRING & NUMERIC VALUES CAN OPERATE TOGETHER WITH *(REPEATED VALUES ARE PRINT)
A,B=2,3
Txt="@"
print(2*Txt*3)




#STRING & STRING CAN OPERATE WITH +
#CONCATINATION
A,B="2",3
Txt="@"
print((A+Txt)+B)


#NUMERIC VALUES CAN OPERATE WITH ALL ARITHMETIC OPERATORS
A,B=2,3
C=4
print(A+B*C)

#ARITHMETIC EXPRESSION WITH INTEGER AND FLOAT WILL RESULT IN FLOAT
A,B=10,5.0
C=A*B
print(C)


#RESULT OF DIVISION OPERATOR WITH TWO INTEGERS WILL BE FLOAT
A,B=1,2
C=A/B
print(C)

#INTEGER DIVISION WITH FLOAT AND INT WILL GIVE INT DISPLAYED AS FLOAT
A,B=1.5,3
C=A//B
print(C,A/B)


#FLOOR GIVES CLOSET INTEGER,WHICH IS LESSER THSN OR EQUAL TO THE FLOAT VALUE
#RESULT OF(A//B) IS SAME AS FLOOR(A/B)

A,B=12,5
C=A//B #DIVIDE  is 2.4 AND CLOSETS INTEGER is 2
#output is 2
print(C)



#REMAINDER IS NEGATIVE WHEN DENOMINATOR IS NEGATIVE
A,B=-5,2
C=A%B
print(C)#OUTPUT IS 1 BECAUSE OF(-,+ =+)

A,B=5,2
C=A%B
print(C)#OUPUT IS 1 BECAUSE OF (+,+ =+)

A,B=5,-2
C=A%B
print(C)#OUTPUT IS -1 BECAUSE OF(+,- =-)